name: External Contributions

on:
  pull_request

jobs:
  check-membership:
    runs-on: ubuntu-latest
    steps:

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'Cockroach Labs'
          body-includes: Files changed

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            <h3>${{ github.event.pull_request.user.login }}</h3>
